### ISSUE TITLE
[BLL] basic job

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/BALIN#100]
@budi7 please write down all sub jobs here

**Comment by budi7** [comment]
- Product
  Save product
  Saving Product’s Categories
  Saving Product’s Attributes
  Saving Product’s Images   
- Deleting Product
  Delete Product’s Categories
  Delete Product’s Attributes
  Delete Product’s Images
  Delete Product’s Prices
  Delete Product’s Discounts
- Create new price
  Count HPP
  Save Price
- Create new discount
  Count HPP
  Save Discount
- Add New Supplier
  Save Supplier
- Add New Customer
  Saving Customer
  Send Email Validation
  Validate Email
  Expire Link
  Resend Email Validation
  Send Email Validated
- Customer Change email address
  Saving Customer
  Send Email Validation
  Validate Email
  Expire Link
  Resend Email Validation
  Send Email Validated
- Add new courier
  Save Courier
  Save Courier’s Branch
- Deleting courier
  Delete Courier
  Delete Courier’s Branch
- Save Transaction (sell)
  Recalculate On Hold Stock
  Recalculate Current Stock
  Recalculate Reserved Stock
  Save Stock
  Saving Shipping Information
  Send Email Billing
- Save Transaction (buy)
  Recalculate On Hold Stock
  Recalculate Current Stock
  Recalculate Reserved Stock
  Save Stock
- Payment confirmation
          Update transaction status
          \* Recalculate On Hold Stock
          \* Recalculate Current Stock
          \* Recalculate Reserved Stock
          \* Save Stock
         Send email payment accepted
         Recalculate Poin (payment method)
         Grant Reward Poin (referral code)
         Save Poin
- Save shipment
         Update transaction status
          \* Recalculate On Hold Stock
          \* Recalculate Current Stock
          \* Recalculate Reserved Stock
          \* Save Stock ()
         Send email tracking shipment
- Update transaction complete status
  Update transaction status(item delivered)
  Send email thanks

**Comment by chelsymooy** [comment]
- [x] Check Stock (construct in check model)

**Comment by chelsymooy** [comment]
- [x] Recalculate Stock
