### ISSUE TITLE
[BLL] business flow through events and listeners

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/BALIN#101]
@budi7 , please write here as well all main jobs (which is hire as event)
Also write down listener

**Comment by chelsymooy** [comment]
@budi7 , write down policies here
https://github.com/ThunderID/BALIN/wiki/%5BPOLICIES%5D-In-web-arch

**Comment by budi7** [comment]
https://github.com/ThunderID/BALIN/wiki/%5Btransaction%5D-Roles
