### ISSUE TITLE
Policy

### ISSUE THREAD

**Issue by erickmo** [ThunderID/BALIN#134]
# Policy tidak terbaca yg terbaru

casenya adalah 
- policy awal "item for one package" = 2
- saya sudah set "item for one package" ke 1, tapi waktu sy beli 2 masih di charge 1 saja
- di cms policy.create inputannya jadi multiple
- di cms policy.index data jadi multiple

**Comment by chelsymooy** [comment]
Untuk Policy, disimpan dalam bentuk log sehingga datanya multiple (alasan tidak berubah karena tanggal di set 04 Dec 2015)

Solusi : 
Tanggal mulai diubah menjadi 12 Dec 2015 (sudah diimplementasikan)

![bggggg](https://cloud.githubusercontent.com/assets/5895063/11760922/4f22836a-a0e1-11e5-977a-9689df24a513.png)
