### ISSUE TITLE
[ASK] Use Case Diagram

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/BALIN#3]
based on wiki : https://github.com/ThunderID/BALIN/wiki/Use-Case-Design
- [x] Colour of the line (red, blue, green, yellow) describe .. ? 
  nothing to describe,  instead of using full of black line.
- [x] Did admin can do login and shop via front end ? 

Found out easier to understand UC Diag like this : http://www.javajotter.net/uml/interview_questions/extendandinclude.JPG or http://accelerateddevelopment.ca/blog_images/UCD,%20retail%209.png

**Comment by chelsymooy** [comment]
Colour line : I tot it has anything to do with ACL (Somehow it helped to write reusable function).

Admin do shop : tot u have to add line (mark or something) in UC Diag

**Comment by budi7** [comment]
Colour line :  yes it's. legend added.

**Comment by budi7** [comment]
added admin do shop
