### ISSUE TITLE
[ASK] ERD

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/BALIN#4]
- [x] All tables did not use any timestamps (created_at, deleted_at, updated_at), did they ? 
- [x] Naming field : (table_name_singular)_id were used for foreign key. If it's Primary Key, please use only id. It helped for fast developing in eloquent

[1-2]
i'll do it on developing phase. the draw is only in purpose to ease me. anyway, i'll create the new one later.
- [x] erd revise
- [x] On table product entities, I tot there is typo : skug, should be slug

done
- [x] Should we have settings table, shouldn't we ? (Settings table include : about us, perhaps FAQ, term and condition, upload logo, etc ?)

ok

``` html
Suggestion : 
Name of the tables contains 2 letter, so it shouldn't be too long (ex : coupon_credit_logs)
Please identify the relationship and indexes (you may use sql workbench or something similar, it really help reader to understand the system without questioning the business logic)
```

**Comment by budi7** [comment]
revise :  erd

**Comment by budi7** [comment]
http://1drv.ms/1WJoycY
